### ISSUE TITLE
ConfigurationManager not supported by newer frameworks

### ISSUE THREAD

**Issue by Reptarsrage** [AddictedCS/soundfingerprinting.solr#1]
This has been replaced by IConfiguration in newer versions of asp net. In fact, Azure Functions do not even remotely support ConfigurationManager. Having this as part of your library prevents users from using this in some production scenarios. Dropping this dependency would help a lot.

**Comment by AddictedCS** [comment]
I'm a little puzzled. Where does this dependency come from?

**Comment by AddictedCS** [comment]
Ah I see, didn't notice the issue is on SoundFingerprinting.Solr :). Yeah, I'd love to remove it, but how would you then configure the endpoints? Do you have any examples?

**Comment by Reptarsrage** [comment]
You can keep all the config in xml, or move to json files if you want. Doesn't really matter. To use XML files, you need to add this NuGet package: Microsoft.Extensions.Configuration.Xml. I added the 1.0.0 to my project.json and added a appsettings.xml file.

```
<configuration>
  <configSections>
    <section name="solr" type="SoundFingerprinting.Solr.Config.SoundFingerprintingSolrConfigurationSection, SoundFingerprinting.Solr" />
  </configSections>
  <solr queryBatchSize="50" preferLocalShards="true">
    <server id="tracks" url="http://localhost:8983/solr/sf_tracks" documentType="SoundFingerprinting.Solr.DAO.TrackDTO, SoundFingerprinting.Solr" />
    <server id="fingerprints" url="http://localhost:8983/solr/sf_fingerprints" documentType="SoundFingerprinting.Solr.DAO.SubFingerprintDTO, SoundFingerprinting.Solr" />
  </solr>
</configuration>
```

I then added it as part of configuration like this:

```
var config = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())
    .AddXmlFile("appsettings.xml", optional: false, reloadOnChange: true)
    .Build();
```

Then I can get the section by adding a reference to 'Microsoft.Extensions.Configuration.Binder' and calling:

```
SoundFingerprintingSolrConfigurationSection section = new SoundFingerprintingSolrConfigurationSection();
config.GetSection("solr").Bind(section);
```

You will have to tweak your Configuration object in order to get the binding to work with duplicate keys

**Comment by Reptarsrage** [comment]
Ah, it looks like SolrNet.Ninject is preventing this change.

It appears that this issue can be resolved by targeting multiple frameworks, please see my ~PR  #2~ PR  #3

**Comment by Reptarsrage** [comment]
Nah this isn't going to solve anything. The ConfigurationManager was a red herring - the bigger issue is that this targets net46 and to do some things on azure netstandard/core is required. Since this is not possible for  this project I'll close this issue and the pull request.
